backend:
  name: git-gateway
  repo: sne-syn/net-cms-gatsby
  branch: master

media_folder: static/assets
public_folder: /assets
collections:
    - name: 'overview' 
      label: 'Overviews'
      label_singular: 'Overview Item'
      editor:
          preview: false
      delete: false
      preview_path: 'overview'
      files:
          - label: 'Overviews'
            name: 'overviews'
            file: 'data/overview.json'
            fields:
                - label: Overviews
                  name: overviews
                  widget: list
                  allow_add: true
                  fields:
                      - { label: 'Title', name: 'title', widget: 'string' }
                      - label: 'Image'
                        name: 'image'
                        widget: 'object'
                        fields:
                            - { label: 'Image', name: 'main', widget: 'image' }
                            - { label: 'Image Alt', name: 'alt', widget: 'image' }
                      - { label: 'Text', name: 'body', widget: 'string' }
