backend:
  name: git-gateway
  repo: sne-syn/net-cms-gatsby
  branch: master

media_folder: static/assets/overviews
public_folder: /assets/overviews
collections:
  - name: 'homepage content' 
    label: 'Homepage Content'
    label_singular: 'Homepage Item List'
    editor:
      preview: false
    delete: false
    preview_path: 'homepage'
    files:
      - label: 'Overviews'
        name: 'overviews'
        file: 'data/overview.json'
        fields:
          - label: Overviews
            name: overviews
            widget: list
            allow_add: true
            fields:
              - {label: 'Id', name: 'id', widget: 'string'}
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Image'
                name: 'image'
                widget: 'object'
                fields:
                    - { label: 'Image', name: 'main', widget: 'image' }
                    - { label: 'Image Alt', name: 'alt', widget: 'string' }
              - { label: 'Text', name: 'body', widget: 'string' }
              - { label: 'Url', name: 'url', widget: 'string' }
      - label: 'Promos'
        name: 'promos'
        file: 'data/promo.json'
        fields:
          - label: Promos
            name: promos
            widget: list
            allow_add: true
            fields:
              - {label: 'Id', name: 'id', widget: 'string'}
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Text', name: 'body', widget: 'string' }
              - { label: 'Url', name: 'url', widget: 'string' }
